# Generated by Django 3.0.3 on 2020-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
