# Generated by Django 3.0.3 on 2020-02-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0003_auto_20200214_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
