# Generated by Django 3.0.3 on 2020-02-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0004_auto_20200214_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[(1, 'Accomodation'), (2, 'Travel')], default=1, max_length=264),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='kumarkom', max_length=264),
        ),
    ]
