# Generated by Django 3.0.3 on 2020-02-15 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0005_auto_20200215_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.IntegerField(choices=[(1, 'Home Stay'), (2, 'Transport'), (3, 'Travel Agency'), (4, 'Restaurant'), (5, 'Ayurvedha'), (6, 'other')], default=1),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(default='kumarakom', max_length=264),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Basic.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
